site_name: lumen-ourworldindata
site_description: Chat with Our World In Data
repo_url: https://github.com/holoviz-topics/lumen-ourworldindata
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: {icon: material/weather-night, name: Dark mode}
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: {icon: material/weather-sunny, name: Light mode}
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - The catalog: catalog.md
  - Examples: examples.md
  - Extending Lumen: extending-lumen.md
  - API reference: api.md
  - Limitations: limitations.md
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc: {permalink: true}
  - pymdownx.details
  - pymdownx.superfences
